server:
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
    mongodb:
      host: ${MONGODB_URL}
      database: venda
      auto-index-creation: true
eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
application-version: 1.0

application:
  service:
    produto:
      url: http://produto-service:8080
      endpoint: ${application.service.produto.url}/produtos
    cliente:
      url: http://cliente-service:8080
      endpoint: ${application.service.cliente.url}/clientes